#!/bin/bash -ue

#-------------------------------------------------------------------------------
# Copyright (C) 2021, HENSOLDT Cyber GmbH
#
# Set variables for the specific analysis project.
#-------------------------------------------------------------------------------

unset_axivion_config () {
    unset PROJECTNAME
    unset TARGETS
    unset BUILD_DIR
}

set_axivion_config() {
    PROJECTNAME=LibsAnalysis

    # The TARGETS variable defines the CMake build targets and outfiles for 1-n
    # analysis projects. Usually the targets are components of a TRENTOS system.
    # The name of the analysis project will be "PROJECTNAME_TargetName".
    declare -Ag TARGETS=(

        # [TargetName]="<BuildTarget> <OutfileInBuildDir>"

        [Main]="analysis test/analysis/libanalysis.so"
    )

    BUILD_DIR="/home/user/build_analysis"
}

set_axivion_config
